# Generated by Django 4.0.5 on 2023-04-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='phonenumbe100',
            new_name='phonenumber100',
        ),
    ]
