# Generated by Django 4.0.5 on 2023-04-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phonenumbe100_feedback_phonenumber100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name20', models.CharField(max_length=40)),
                ('username20', models.CharField(max_length=40)),
                ('password20', models.CharField(max_length=50)),
                ('phonenumber20', models.CharField(max_length=10)),
                ('email20', models.CharField(max_length=40)),
                ('name30', models.CharField(max_length=40)),
                ('phonenumber30', models.CharField(max_length=10)),
                ('name40', models.CharField(max_length=40)),
                ('phonenumber40', models.CharField(max_length=10)),
            ],
        ),
    ]
